### ISSUE TITLE
Problem with Joomla 1.5

### ISSUE THREAD

**Issue by afrugone** [cognidox/OTRS-Joomla-Gateway#10]
Hi,

First, many thanks for making this OTRS-Joomla Gateway, I installed it without any problem, but when I try to generate a new ticket indoesn´t load the TO: field, I've to syscronize something?

My configuration is:
Joomla 1.5.22
Otrs 3.0.6
Gateway version 0.9.0

Thanks for your help.
Regards
Alfredo

**Comment by vittala** [comment]
Hi Alfredo

The To field is based on the queues that are available to the user logging into Joomla. How have you configured the gateway to authenticate users to OTRS? Have you given access to queues in OTRS to the user you're logging in with?

Regards
Vittal

**Comment by afrugone** [comment]
Hi Vittal,

Many thanks for your answer. I think I missed something, I've configured the gateway in Otrs and Joomla, but I can't find how syncronize users, I've a Joomla site with many users and now I'm adding OTRS to give support to these users, so how Otrs will discover these users?

Thanks again and best regards
Alfredo

**Comment by vittala** [comment]
Hi Alfredo

The gateway doesn't synchronise users, rather it allows you to map a Joomla user onto an OTRS customer user either by their login, or, by their email address. Note that this means you must create customer users in OTRS for the Joomla users that need to use OTRS.

In the component's parameters on Joomla, you'll see the "User Mapping" selection, which can be set to either "Login" or "Email". Select the appropriate value for your setup.  If set to login, the user's login on both Joomla and OTRS must match for OTRS to recognise them. If set to email, the user's email address on both OTRS and Joomla must match for OTRS to recognise them.

Hope this make sense
Vittal

**Comment by afrugone** [comment]
Thanks for your help, customer users are created at Joomla as they register in Joomla site, how could be the best way to replicate these users to OTRS, import users to the database user in OTRS? or i must manually recreate customer users in OTRS, what about the passwords, must be the same in both sides? I don't know the custmer user passwords.

Thanks
Alfredo

**Comment by vittala** [comment]
Hi Alfredo

At the moment, you'll need to manually create an account for them in OTRS. If login and email address are the same between the two, then you don't have to worry about the OTRS password being the same, so you can set the OTRS passwords to something random.

The _best_ way to sync users would be to have OTRS use the Joomla database as a user source. In this scenario, as users registered in Joomla, they'd become available to OTRS. However, this requires that a custom OTRS customer user module is written. We're mulling the idea over as something to add to the gateway in the future.

Regards
Vittal
