### ISSUE TITLE
Ticket List Layout doesn't show information

### ISSUE THREAD

**Issue by OpenNingia** [cognidox/OTRS-Joomla-Gateway#13]
I am testing this gateway between Joomla and Otrs. Submitting ticket works fine and from OTRS backend I can reply to them.

However on the Joomla frontend I cannot manage to interact with an existing ticket.

After clicking on a ticket in the ticket list view here what I get.
http://imm.io/56md

![Joomla My Ticket View](http://i.imm.io/56md.png)

If I try to reply to that ticket I get an alert with the string 'OTRS_TICKET_ACCESS_DENIED' nothing more.

How can I solve this?

**Comment by OpenNingia** [comment]
I've got it. The issue is that the ticket contains HTML data. Passing HTML data via SOAP caused a format exception.
I fixed it just by passing the ticket body as CDATA.

file: JoomlaGateway.pm
function: GetTicket

``` php
if (%ArticleBodyData) {
    $item->{'Body'} = '<![CDATA[' . $ArticleBodyData{'Content'} . ']]>'
    $item->{'Type'} = 'text/html';
}
```

**Comment by vittala** [comment]
Hi OpenNingia

Many thanks for that patch. I'll try and replicate it here and add it to the tree.

Regards
Vittal

**Comment by vittala** [comment]
Hi OpenNingia

I've not been able to replicate your issue on my local test system. Can you let me know the following about your setup:
- The actual ticket text that caused the problem
- The version of the SOAP::Lite module installed on the OTRS server
- The version of OTRS being used
- Where the format exception error was raised (Joomla side or OTRS side), and if possible the exact error raised
- The version of Joomla being used
- The PHP version used to run Joomla
- The version of libxml (available from the Joomla PHP system info page) used

Regards
Vittal

**Comment by OpenNingia** [comment]
Hi Vittal,

my setup is:
- OS: Ubuntu 8.04 Server
- Kernel: Linux 2.6.24-26-server
- SOAP::Lite ( libsoap-lite-perl ): 0.69-2
- As far as I understand the exception was Joomla Side
- The error: SOAP Fault: (faultcode: Client, faultstring: SOAP-ERROR: Encoding: Violation of encoding rules)
- Joomla version: 1.5.23
- PHP version: 5.2.4-2ubuntu5.10
- libxml version: 2.6.31

More details: request data and response data

```
REQUEST:
some_usersome_passJoomlaGatewayObjectGetTicketTicketID4CustomerUserLogintest01CustomerUserIDtest01Permissionro 
END_REQUEST

RESPONSE:
3138.2 KBytesimage/jpeg4-gandolf-math-mathfail1-1.jpg39077238.2 KBytesimage/jpeg4-gandolf-math-    mathfail1.jpg390777Softwareclosed successfultext/html72011-04-20     11:10:56PGh0bWw+PGhlYWQ+PG1ldGEgaHR0cC1lcXVpdj0iQ29udGVudC1UeXBlIiBjb250ZW50PSJ0ZXh0L2h0bWw7IGNoYXJzZX  Q9dXRmLTgiLz48L2hlYWQ+PGJvZHkgc3R5bGU9ImZvbnQtZmFtaWx5OkdlbmV2YSxIZWx2ZXRpY2EsQXJpYWwsc2Fucy1zZXJpZj   sgZm9udC1zaXplOiAxMnB4OyI+PHA+PHN0cm9uZz5Qcm92aWFtbyBxdWFsY29zYSBkaSBwaXUnIGVsYWJvcmF0bzwvc3Ryb25  nPjwvcD4NCjxwPsKgPC9wPg0KPHA+PHN0cm9uZz48ZW0+VGVudG8gYW5jb3JhIGRpIGludmlhcmUgdW4gYWxsZWdhdG8uPC9l  bT48L3N0cm9uZz48L3A+PC9ib2R5PjwvaHRtbD4=Test 01 <test01@email.com>24text/html82011-04-20 11:11:17<html><head>  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/></head><body style="font-  family:Geneva,Helvetica,Arial,sans-serif; font-size: 12px;"><p>mi ero scordato una cosa!!!</p></body></html>Test 01   <test01@email.com>text/html92011-04-20 11:17:20Dear Test 01,
END_RESPONSE
```

best regards,
Daniele

**Comment by vittala** [comment]
Thanks Daniele

I'll have a look into it. I suspect the problem lies in one of SOAP::Lite or libxml. I don't see problems with SOAP::Lite 0.712 and libxml 2.7.6.

Regards
Vittal

**Comment by OpenNingia** [comment]
Sorry I always close the issue by mistake.
However I also tried with Ubuntu 10.10 and newest SOAP::Lite and there I experienced another problem ( that you also have troubleshooted in the installation PDF ) where I was not able to connect to OTRS from Joomla.

( The sysread vs read issue in SOAP::Lite ). So I downgraded to Ubuntu 8.04 and it works fine, except this issue.

**Comment by OpenNingia** [comment]
This is fixed with last version of SOAP::Lite library ( 0.713 if i remember well )
