### ISSUE TITLE
Type field is missing

### ISSUE THREAD

**Issue by Mask001** [cognidox/OTRS-Joomla-Gateway#14]
Hello everyone,
while testing the OTRSGateway I noticed that is missing fields ... I wonder if you could add the field Type (type of ticket) when you create a new ticket ...
Thanks

**Comment by vittala** [comment]
Hi Mask001,

We'll look into this for a future release. 

Regards
Vittal
(note to self - requires the OTRS side examine the Ticket::Type setting to validate if types are sent over and accepted)

**Comment by Mask001** [comment]
Hi Vittala,

I thank you for the quick response, I would really appreciate if you could inform me when the next release will be issued.

Regards
Mask

**Comment by vittala** [comment]
Hi Mask

We don't have a release date scheduled for the next version. Our focus for the next release is native Joomla 1.6 support, after which, we'll be looking at additional functionality such as better field handling.

Regards
Vittal

**Comment by vittala** [comment]
Hi Mask

We've released version 0.9.1 of the package which has support both for Joomla 1.6 and this missing ticket type field. If you update both the Joomla and OTRS components, this should be fixed for you.

Regards
Vittal
