### ISSUE TITLE
"New ticket" and "reply to ticket" trouble

### ISSUE THREAD

**Issue by Quibard** [cognidox/OTRS-Joomla-Gateway#15]
I've installed on Joomla 1.5 and OTRS 3.08, and i think the basic stuff works wonderfully well. I do have issues with creating new tickets on IE 9, and replying to tickets in Firefox (and IE).

I checked that JSON is switched on, I'm using php 5.3.3 on Centos 5.5.

Where should I start looking to fix this?

thanks!

**Comment by vittala** [comment]
Hi Quibard

Can you let me know what exactly the issue is in both cases so we can characterise this issue.

With IE9, when creating tickets, which of the following apply:
- Does the form appear correctly, with the pulldowns populated correctly from OTRS?
- Is it possible to add attachments using the form?
- When submit is clicked, is the ticket submitted to OTRS?
- When submit is clicked, does the form close and the new ticket appear?
- Is IE 9 raising any javascript errors?

When replying to tickets, which of the following apply:
- Does the reply window popup when you click the reply button?
- If the window pops up, is the text area editable?
- Can attachments be added to the ticket?
- Does the window close when Submit is clicked?
- Does the ticket update in OTRS when Submit is clicked?
- Does the ticket vie refresh in Joomla when Submit is clicked?

Regards
Vittal

**Comment by Quibard** [comment]
Hi Vittala,

Thanks for responding so quickly!

The webpages can be open to internet, if you have a direct email I'd be happy to show you. I have a gmail account with my github username/alias.

In any case answers to your questions:
With IE9, when creating tickets, which of the following apply:
- Does the form appear correctly, with the pulldowns populated correctly from OTRS?                yes
- Is it possible to add attachments using the form?                                yes
- When submit is clicked, is the ticket submitted to OTRS?                         no
- When submit is clicked, does the form close and the new ticket appear?                   no

If any information is missing, like subject, queue etc. error messages are provided

On replying to tickets:
- Does the reply window popup when you click the reply button?                      yes
  - If the window pops up, is the text area editable?                                yes
  - Can attachments be added to the ticket?                                  yes
  - Does the window close when Submit is clicked?                                no
  - Does the ticket update in OTRS when Submit is clicked?                           no
  - Does the ticket vie refresh in Joomla when Submit is clicked?                            I'm not sure what you mean, but I assume that because the previous answers are No, this isn't really important?

Cheers,
aart
-----Original Message-----

**Comment by vittala** [comment]
Hi Aart

I've had a quick look at your site, and here are some possible places to look:

IE9 problems seem to be stemming from TinyMCE (the editor plugin used by Joomla). This is raising all sorts of Javascript errors and appears to be a known problem with Joomla 1.5 and IE9. Possible fixes are:
- Try using another editor plugin in Joomla (e.g. http://www.joomlacontenteditor.net/) and disabling the TinyMCE plugin
- Manually update the TinyMCE plugin in Joomla to the 3.2.7 branch (https://github.com/tinymce/tinymce/tree/3.2.7) - No guarantee it'll work with Joomla though

As for replying, I see Mootools go into a loop when viewing the reply popup. I also see you have jQuery used. Can you temporarily disable your jQuery code by removing the relevant script elements from your template and seeing if reply works.

Regards
Vittal

**Comment by Quibard** [comment]
Vittal, thanks for the support! Ill look into your tips today!

I'm curious to understand how you analysed these issues, may I ask how you did it?

Thanks,
Aary
Sent from my Nexus One

vittala reply@reply.github.com wrote:

Hi Aart

I've had a quick look at your site, and here are some possible places to look:

IE9 problems seem to be stemming from TinyMCE (the editor plugin used by Joomla). This is raising all sorts of Javascript errors and appears to be a known problem with Joomla 1.5 and IE9. Possible fixes are:
- Try using another editor plugin in Joomla (e.g. http://www.joomlacontenteditor.net/) and disabling the TinyMCE plugin
- Manually update the TinyMCE plugin in Joomla to the 3.2.7 branch (https://github.com/tinymce/tinymce/tree/3.2.7) - No guarantee it'll work with Joomla though

As for replying, I see Mootools go into a loop when viewing the reply popup. I also see you have jQuery used. Can you temporarily disable your jQuery code by removing the relevant script elements from your template and seeing if reply works.

Regards
Vittal

## 

Reply to this email directly or view it on GitHub:
https://github.com/cognidox/OTRS-Joomla-Gateway/issues/15#comment_1340888

**Comment by vittala** [comment]
Hi Aart

IE 9 has a set of developer tools that can be used to debug pages - http://msdn.microsoft.com/en-us/ie/aa740478

For Firefox, I use Firebug (http://getfirebug.com/), Safari and Chrome also have built in developer console.

All of the above allow you to track scripting errors in pages as you view them, and are invaluable when developing sites.

Hope this helps

Regards
Vittal

**Comment by Quibard** [comment]
Hi Vittal,

Thanks to your pointers about firebug, I found some errors relating to mootools. When I googled those, there was a hint by someone about components/plugins that hardcode the path to the mootools.js file, even though other plugins try to update it.

When I commented out line 14 of com_otrsgateway/views/ticket/tmpl/reply.php, so that it wouldn't include media/system/js/mootools.js I could start to reply to the issues!

Now to test, test and test some more !

Thanks!

Aart

-----Original Message-----

**Comment by vittala** [comment]
Hi Aart

Can you replace the mootools line with this line:

JHTML::_('behavior.mootools');

and let me know if reply works.

Regards
Vittal

**Comment by Quibard** [comment]
Hi Vittal,

Yes, that works.

Cheers,
Aart

-----Original Message-----

**Comment by vittala** [comment]
Hi Aart

I've checked that update into github so it'll be in future releases.

As for the IE9 issue, you may be able to use the TinyMCE editor that comes with Joomla if you force IE9 into  IE8 or IE7 compatibility mode by adding a header into your page template. This page on MSDN discusses it: http://msdn.microsoft.com/en-us/library/cc288325%28v=vs.85%29.aspx

Regards
Vittal

**Comment by Quibard** [comment]
As far as I'm concerned, this issue is solved, so I'm closing.

thanks for the quick support!
