### ISSUE TITLE
Reply button not translated

### ISSUE THREAD

**Issue by Quibard** [cognidox/OTRS-Joomla-Gateway#17]
Admittedly a minor issue;
I translated the language file to Dutch. Pretty straightforward, but...
There are 2 reply buttons, one to the right of the message and one below. The button to the right contains my Dutch text, but the button below the issue text does not, that remains English.

I think this is caused by views/ticket/tmpl/default.php, where the last line reads
<a class="modal button" href="index.php?option=com_otrsgateway&task=replyForm&ticketID=<?php echo $this->ticket->TicketID; ?>" rel="{handler:'iframe',size:{x:650,y:450},ajaxOptions:{}}">Reply</a>

If I change the >Reply< to >AnotherWord<, the button shows "AnotherWord".

**Comment by Quibard** [comment]
Replacing >Reply< in the last line with 

> <?php echo JText::_('OTRS_REPLY');?><
> fixes the issue.

**Comment by vittala** [comment]
Thanks Aart, I've checked this into the tree now.

Regards
Vittal

**Comment by Quibard** [comment]
in that case, let's close the issue.
