### ISSUE TITLE
Reply button not working

### ISSUE THREAD

**Issue by digitalreal** [cognidox/OTRS-Joomla-Gateway#18]
Hello!
thanks for the great bridge!
i installed and everything works but the reply button.
json is enabled (v1.2.1),  php 5.2.6 is running.
i tried it with firefox and safari on a mac.
when i click on reply, another page opens, clean white with a reply form. writing some text and clicking on submit does nothing. when i click cancel or hit the back button of the browser i see a new entry.
i tried to switch off the mootools call as described in the other issue but nothing happened.
please help!
thanks in advance,
ingo

**Comment by vittala** [comment]
Hi Ingo

What version of Joomla are you running, and what is the editor plugin active on your site?

When you say "another page opens" - is it a popup window over the bug, or does it take up the whole page?

Regards
Vittal

**Comment by digitalreal** [comment]
Hi Vittal,
thanks for your fast reply!
running joomla 1.5.23.
the click on reply took me to t new whole page.
i found a solution through trial and error (although i got nearly mad!):
there was a call to a google hosted javascript (although js was already locally called):

<script type="text/javascript">
google.load("jquery", "1"); 
</script>

i removed it and now it's working.
thanks again,
best,
ingo
