### ISSUE TITLE
Ticket::Frontend::CustomerTicketMessage###Queue does not work with OTRS-Joomla-Gateway

### ISSUE THREAD

**Issue by Samifighter** [cognidox/OTRS-Joomla-Gateway#20]
If you set Ticket::Frontend::CustomerTicketMessage###Queue to yes and set Ticket::Frontend::CustomerTicketMessage###QueueDefault to something, the New Ticket page in Joomla still allows the user to select a Queue.

**Comment by vittala** [comment]
Hi

Which version of OTRS are you using?

Regards
Vittal

**Comment by Samifighter** [comment]
Hi,

I'm using version 3.0.10.

Best regards

Sven Teichmann

**Comment by vittala** [comment]
Thanks Sven

From the initial looks of things, we're not filtering the list of queues returned by GetTicketQueues in Kernel::System::JoomlaGateway. It should be a case of adding some filtering on the list based on whether both 
Ticket::Frontend::CustomerTicketMessage###Queue and Ticket::Frontend::CustomerTicketMessage###QueueDefault are set.

We'll look into it.

Regards
Vittal

**Comment by vittala** [comment]
Hi Sven

I've checked in a possible fix for this as 39ba533. You can either apply this change, or use the whole file from https://github.com/cognidox/OTRS-Joomla-Gateway/blob/39ba5330a9d7a7fb045d8e5f93c163739698cba7/otrs_joomla_module/Kernel/System/JoomlaGateway.pm.

The update will be included in the next release.

Regards
Vittal

**Comment by vittala** [comment]
This update has now been included in release 0.9.2.

Regards
Vittal
