### ISSUE TITLE
Conflict between otrs-joomla-gateway and some templates

### ISSUE THREAD

**Issue by scibi** [cognidox/OTRS-Joomla-Gateway#22]
OTRS-Joomla-Gateway uses 'message' as a name and id of editor in ticket submission form. This conflicts with some templates, because it's quite common word. It would be better to change it to something like 'otrsmessage'. I had to do that in my installation to make it work.

**Comment by vittala** [comment]
Hi

Thanks for the suggestion, seems like a good idea. We'll make this change in the next release.

Regards
Vittal

**Comment by vittala** [comment]
Hi,

The names for the message and reply fields have been changed in 0.9.2 to otrsmessage and otrsreplytext respectively.

Thanks for the suggestion.

Regards
Vittal
