### ISSUE TITLE
Attachments aren't shown when adding them

### ISSUE THREAD

**Issue by OpenNingia** [cognidox/OTRS-Joomla-Gateway#23]
On Submit form and Reply form you can Select a File and then add the attachment, the system is supposed to show the file name on a list so the user can check which files he has attached successfully. Sadly this doesn't work in Submit form neither in Reply form.
However after submitting a ticket or a reply, the attachment are correctly shown in the resulting view.

Joomla 1.5
OTRS 3.1.0
OTRS-Joomla-Gateway 0.9.1
OS: Centos5

**Comment by vittala** [comment]
Hi

Have you got a URL where I can see this in action? Could you also confirm what browser you're using when you see this happen.

It's possible this is down to the template you're using and the javascript you're using on the page.

Regards
Vittal

**Comment by OpenNingia** [comment]
This is hard, because the website is not published on the internet yet ( we've issues to solve before that )
I can provide you with the template thou, or with the source ( right click -> view page source... ) of any page you need.

**Comment by vittala** [comment]
Hi

It'll be tricky to diagnose without seeing the system in action. Attach your template as a zip in a private message to me and I'll see if it works here.

Regards
Vittal

**Comment by OpenNingia** [comment]
I've set up other templates (rhuk_milkyway and JA_Purity, quite the Joomla standard ones) and the problem remains.

**Comment by vittala** [comment]
This looks like another symptom of #24, with a redirect happening rather than the proper JSON return. I suggest we close this ticket, and carry on diagnosing on #24, since solving that should solve this.

Regards
Vittal

**Comment by OpenNingia** [comment]
seconded that :)
