### ISSUE TITLE
Can't communicate with otrs using soap in IIS 7.5/Apache 5.2.14

### ISSUE THREAD

**Issue by jhgarcia** [cognidox/OTRS-Joomla-Gateway#27]
Hello,
I installed everything just fine (otrs/joomla) but when configuring the plugin I receive the following: •SOAP Fault: (faultcode: HTTP, faultstring: Error Fetching http headers). In the log there's nothing and if you access the link directly, it gives you: The page cannot be displayed because the server requires a Content-Length header in the request.

Any ideas? I'm running both Joomla and OTRS from IIS 7.5 

Thanks for all the help you guys could provide.

**Comment by vittala** [comment]
Hi

Which versions of OTRS, Joomla and PHP are you using?

Also, you say you're using IIS 7.5/Apache 5.2.14 - I take it that Joomla is running through IIS and OTRS running through Apache on a port other than 80? If that is the case, what do you have as the "RPC URL" in the gateway parameters?

Is there anything in the OTRS error log?

Regards
Vittal

**Comment by jhgarcia** [comment]
Hi vittala,
I'm using Joomla 1.7 and both Joomla and OTRS are running from IIS on port 80. Joomla running under one website/ip and otrs under a second website/ip. The RPC URL is http://my2ndipaddress/otrs/rpc.extended.pl. Nothing is showing up in the otrs error log.
My otrs version is 3.0.11

**Comment by vittala** [comment]
Hi

What is the version number of PHP that you're running and how is it configured to run under IIS (e.g. non-thread-safe under FastCGI)?

What is the version of perl that you're running (e.g. ActivePerl) and how's IIS configured to run OTRS?

When you said "access the link directly" earlier, did you mean the RPC URL?

Regards
Vittal

**Comment by jhgarcia** [comment]
My PHP version is 5.2.14, FastCGI, Perl5.12.3 (StrawberryPerl), OTRS is configured under a subdomain with its dedicated ip a virtual directory for otrs and another for otrs-web.

Yes, if I go and paste the RPC URL directly into the browser, then I receive that "Content-Length header in the request" and its understandable since no data is being sent.

Thanks in advanced for all your time!

**Comment by vittala** [comment]
Hi

It's possible that this is due to OTRS being too slow to respond to Joomla. Try increasing default_socket_timeout in your php.ini file to a large value (e.g. 600). See http://www.php.net/manual/en/filesystem.configuration.php#ini.default-socket-timeout

If this doesn't help, it may be that a packet trace of the request between Joomla and OTRS is needed to debug this. We haven't tested the component under your particular Windows configuration, so a packet trace will show up any IIS specific connection issues.

Regards
Vittal

**Comment by vittala** [comment]
Another thing to verify is that the SOAP::Lite module installed with StrawberryPerl is suitable for OTRS. You can check by running the perl script <otrs_directory>\bin\otrs.CheckModules.pl

The script will list all the required and optional modules and whether the installed version is OK. If SOAP::Lite is not OK, use StrawberryPerl's CPAN client to install the latest SOAP::Lite module.

Regards
Vittal

**Comment by vittala** [comment]
Hi 

I've had a further poke around on a system setup similar to yours. It looks like the error may come from the CGI handler hanging while getting access to the CGI environment.

If after checking the SOAP::Lite module is correct, and the problem still occurs, try the following work-around:
- Edit &lt;otrs&gt;\bin\cgi-bin\rpc.extended.pl
- After the line starting <code>$CommonObject{LinkObject}         = </code>, add the line:
  <code>$CommonObject{WebRequest} = {};</code>
- Save the file

This file is part of the OTRS Gateway package so won't affect the rest of OTRS' functionality.

Regards
Vittal

**Comment by jhgarcia** [comment]
Vittala,

The work-around did the trick! Thanks so much for all your time and help.

Best regards,
John
