### ISSUE TITLE
Unable to create ticket

### ISSUE THREAD

**Issue by gartenlos** [cognidox/OTRS-Joomla-Gateway#28]
Der Versuch Joomla 1.5.25 mit der aktuellen OTRS Version zu verknüpfen schlägt beim Absenden eines Tickets leider 
fehl. Ich kann die Queses auswählen und auch den Ticket Text hinterlegen, nur beim Absenden kommt die Meldung "Unable to create ticket" 
Die Anzeige meiner Ticket funktioniert in Joomla, hier kann ich auch Antworten verfassen ! ;-)
Schön wäre noch wenn ein noch nicht verhandener Kunde automatisch in OTRS angelegt wird !

**Comment by vittala** [comment]
Hi

What appears in your OTRS system System Log when you attempt to create a ticket?

Regards
Vittal

**Comment by gartenlos** [comment]
Dienstag, 20.03.2012
Hello, 
80.77.31.172 - - [20/Mar/2012:11:30:36 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 669
80.77.31.172 - - [20/Mar/2012:11:30:36 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 847
80.77.31.172 - - [20/Mar/2012:11:30:36 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 484
80.77.31.172 - - [20/Mar/2012:11:30:36 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 1914
80.77.31.172 - - [20/Mar/2012:11:30:36 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 457
80.77.31.172 - - [20/Mar/2012:11:30:51 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 514
80.77.31.172 - - [20/Mar/2012:11:30:51 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 859
80.77.31.172 - - [20/Mar/2012:11:30:52 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 1914
80.77.31.172 - - [20/Mar/2012:11:30:52 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 457
82.113.121.12 - - [20/Mar/2012:11:33:37 +0100] "POST /otrs/json.pl HTTP/1.1" 200 -
82.113.121.12 - - [20/Mar/2012:11:38:22 +0100] "POST /otrs/json.pl HTTP/1.1" 200 -
80.77.31.172 - - [20/Mar/2012:11:42:24 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 495
82.113.121.12 - - [20/Mar/2012:11:43:39 +0100] "POST /otrs/json.pl HTTP/1.1" 200 -
80.77.31.172 - - [20/Mar/2012:11:46:35 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 495
80.77.31.172 - - [20/Mar/2012:11:47:00 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 623
80.77.31.172 - - [20/Mar/2012:11:47:05 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 669
80.77.31.172 - - [20/Mar/2012:11:47:05 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 859
80.77.31.172 - - [20/Mar/2012:11:47:06 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 484
80.77.31.172 - - [20/Mar/2012:11:47:06 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 1914
80.77.31.172 - - [20/Mar/2012:11:47:06 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 457
80.77.31.172 - - [20/Mar/2012:11:47:17 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 514
80.77.31.172 - - [20/Mar/2012:11:47:17 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 859
80.77.31.172 - - [20/Mar/2012:11:47:17 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 1914
80.77.31.172 - - [20/Mar/2012:11:47:17 +0100] "POST /otrs/rpc.extended.pl HTTP/1.1" 200 457
82.113.121.12 - - [20/Mar/2012:11:48:20 +0100] "POST /otrs/json.pl HTTP/1.1" 2

Herzlichen Grüße aus Hünfelden 

Marc-Oliver Widmann

((ev-it)) it-support & more | Inh. Marc-Oliver Widmann | Hehnerstrasse 7 | 65597 Hünfelden 
Tel. 06431-9499000 Fax 06431-9499009 Umsatz ID-Nr.: DE 195 381 168

Re: [OTRS-Joomla-Gateway] Unable to create ticket (#28) (20-Mrz-2012 11:44)
From:   Vittal Aithal
To:gartenlos

Hi

What appears in your OTRS system System Log when you attempt to create a ticket?

Regards
Vittal

---

**Comment by gartenlos** [comment]
Dienstag, 20.03.2012
Time: Tue Mar 20 11:09:00 2012
 Message: No StateID for 'new'!
 Traceback (304): 
   Module: Kernel::System::Ticket::TicketCreate (v1.542) Line: 419
   Module: Kernel::System::JoomlaGateway::TicketSubmit (unknown version) Line: 419
   Module: Core::Dispatch (unknown version) Line: 137
   Module: (eval) (unknown version) Line: 2816
   Module: (eval) (unknown version) Line: 2801
   Module: SOAP::Server::handle (unknown version) Line: 2767
   Module: SOAP::Transport::HTTP::Server::handle (unknown version) Line: 432
   Module: SOAP::Transport::HTTP::CGI::handle (unknown version) Line: 597
   Module: ModPerl::ROOT::ModPerl::Registry::C_3a_Programme_OTRS_OTRS_bin_cgi_2dbin_rpc_2eextended_2epl::handler (unknown version) Line: 46
   Module: (eval) (v1.14) Line: 204
   Module: ModPerl::RegistryCooker::run (v1.14) Line: 204
   Module: ModPerl::RegistryCooker::default_handler (v1.14) Line: 170
Scalars leaked: 1
Scalars leaked: 1
[Tue Mar 20 11:23:37 2012] json.pl: Subroutine new redefined at C:/Programme/OTRS/OTRS/bin/cgi-bin/json.pl line 65.
[Tue Mar 20 11:23:37 2012] json.pl: Subroutine Dispatch redefined at C:/Programme/OTRS/OTRS/bin/cgi-bin/json.pl line 75.
[Tue Mar 20 11:23:37 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/Programme/OTRS/OTRS/bin/cgi-bin/json.pl line 301.

> > Can't write : No such file or directory <<
> > [Tue Mar 20 11:23:37 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/PROGRA~1/OTRS/OTRS//Kernel/System/Log.pm line 161.
> > [Tue Mar 20 11:23:37 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/PROGRA~1/OTRS/OTRS//Kernel/System/Log.pm line 161.
> > ERROR: OTRS-iPhoneHandle-10 Perl: 5.12.3 OS: MSWin32 Time: Tue Mar 20 11:23:37 2012
> >  Message: No UserID found for 'ticket
> > '!
> >  Traceback (304): 
> >    Module: Kernel::System::User::UserLookup (v1.116) Line: 746
> >    Module: Kernel::System::Auth::Auth (v1.54) Line: 232
> >    Module: Core::Dispatch (unknown version) Line: 136
> >    Module: ModPerl::ROOT::ModPerl::Registry::C_3a_Programme_OTRS_OTRS_bin_cgi_2dbin_json_2epl::handler (unknown version) Line: 61
> >    Module: (eval) (v1.18) Line: 204
> >    Module: ModPerl::RegistryCooker::run (v1.18) Line: 204
> >    Module: ModPerl::RegistryCooker::default_handler (v1.18) Line: 170
> >    Module: ModPerl::Registry::handler (v1.99) Line: 31

[Tue Mar 20 11:23:37 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/Programme/OTRS/OTRS/bin/cgi-bin/json.pl line 301.

> > Can't write : No such file or directory <<
> > [Tue Mar 20 11:23:39 2012] iPhoneBackend.pm: Subroutine new redefined at C:/PROGRA~1/OTRS/OTRS//Kernel/System/DynamicField/iPhone/iPhoneBackend.pm line 83.
> > [Tue Mar 20 11:23:39 2012] iPhoneBackend.pm: Subroutine IsIPhoneCapable redefined at C:/PROGRA~1/OTRS/OTRS//Kernel/System/DynamicField/iPhone/iPhoneBackend.pm line 226.
> > [Tue Mar 20 11:23:39 2012] iPhoneBackend.pm: Subroutine EditFieldRender redefined at C:/PROGRA~1/OTRS/OTRS//Kernel/System/DynamicField/iPhone/iPhoneBackend.pm line 363.
> > [Tue Mar 20 11:23:39 2012] iPhoneBackend.pm: Subroutine EditFieldValueGet redefined at C:/PROGRA~1/OTRS/OTRS//Kernel/System/DynamicField/iPhone/iPhoneBackend.pm line 440.
> > [Tue Mar 20 11:23:39 2012] iPhoneBackend.pm: Subroutine EditFieldValueValidate redefined at C:/PROGRA~1/OTRS/OTRS//Kernel/System/DynamicField/iPhone/iPhoneBackend.pm line 510.
> > Scalars leaked: 1
> > [Tue Mar 20 11:28:37 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/Programme/OTRS/OTRS/bin/cgi-bin/json.pl line 301.
> > Can't write : No such file or directory <<
> > [Tue Mar 20 11:28:37 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/PROGRA~1/OTRS/OTRS//Kernel/System/Log.pm line 161.
> > [Tue Mar 20 11:28:37 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/PROGRA~1/OTRS/OTRS//Kernel/System/Log.pm line 161.
> > ERROR: OTRS-iPhoneHandle-10 Perl: 5.12.3 OS: MSWin32 Time: Tue Mar 20 11:28:37 2012
> >  Message: No UserID found for 'ticket
> > '!
> >  Traceback (304): 
> >    Module: Kernel::System::User::UserLookup (v1.116) Line: 746
> >    Module: Kernel::System::Auth::Auth (v1.54) Line: 232
> >    Module: Core::Dispatch (unknown version) Line: 136
> >    Module: ModPerl::ROOT::ModPerl::Registry::C_3a_Programme_OTRS_OTRS_bin_cgi_2dbin_json_2epl::handler (unknown version) Line: 61
> >    Module: (eval) (v1.18) Line: 204
> >    Module: ModPerl::RegistryCooker::run (v1.18) Line: 204
> >    Module: ModPerl::RegistryCooker::default_handler (v1.18) Line: 170
> >    Module: ModPerl::Registry::handler (v1.99) Line: 31

[Tue Mar 20 11:28:37 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/Programme/OTRS/OTRS/bin/cgi-bin/json.pl line 301.

> > Can't write : No such file or directory <<
> > [Tue Mar 20 11:30:51 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/PROGRA~1/OTRS/OTRS//Kernel/System/Log.pm line 161.
> > [Tue Mar 20 11:30:51 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/PROGRA~1/OTRS/OTRS//Kernel/System/Log.pm line 161.
> > [Tue Mar 20 11:30:51 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/PROGRA~1/OTRS/OTRS//Kernel/System/Log.pm line 161.
> > [Tue Mar 20 11:30:51 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/PROGRA~1/OTRS/OTRS//Kernel/System/Log.pm line 161.
> > [Tue Mar 20 11:30:51 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/PROGRA~1/OTRS/OTRS//Kernel/System/Log.pm line 161.
> > [Tue Mar 20 11:30:51 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/PROGRA~1/OTRS/OTRS//Kernel/System/Log.pm line 161.
> > [Tue Mar 20 11:30:51 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/PROGRA~1/OTRS/OTRS//Kernel/System/Log.pm line 161.
> > [Tue Mar 20 11:30:51 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/PROGRA~1/OTRS/OTRS//Kernel/System/Log.pm line 161.
> > ERROR: OTRS-EXT-RPC-10 Perl: 5.12.3 OS: MSWin32 Time: Tue Mar 20 11:30:51 2012
> >  Message: No StateID for 'new'!
> >  Traceback (304): 
> >    Module: Kernel::System::Ticket::TicketCreate (v1.542) Line: 419
> >    Module: Kernel::System::JoomlaGateway::TicketSubmit (unknown version) Line: 419
> >    Module: Core::Dispatch (unknown version) Line: 137
> >    Module: (eval) (unknown version) Line: 2816
> >    Module: (eval) (unknown version) Line: 2801
> >    Module: SOAP::Server::handle (unknown version) Line: 2767
> >    Module: SOAP::Transport::HTTP::Server::handle (unknown version) Line: 432
> >    Module: SOAP::Transport::HTTP::CGI::handle (unknown version) Line: 597
> >    Module: ModPerl::ROOT::ModPerl::Registry::C_3a_Programme_OTRS_OTRS_bin_cgi_2dbin_rpc_2eextended_2epl::handler (unknown version) Line: 46
> >    Module: (eval) (v1.14) Line: 204
> >    Module: ModPerl::RegistryCooker::run (v1.14) Line: 204
> >    Module: ModPerl::RegistryCooker::default_handler (v1.14) Line: 170
> > [Tue Mar 20 11:47:17 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/PROGRA~1/OTRS/OTRS//Kernel/System/Log.pm line 161.
> > [Tue Mar 20 11:47:17 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/PROGRA~1/OTRS/OTRS//Kernel/System/Log.pm line 161.
> > [Tue Mar 20 11:47:17 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/PROGRA~1/OTRS/OTRS//Kernel/System/Log.pm line 161.
> > [Tue Mar 20 11:47:17 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/PROGRA~1/OTRS/OTRS//Kernel/System/Log.pm line 161.
> > [Tue Mar 20 11:47:17 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/PROGRA~1/OTRS/OTRS//Kernel/System/Log.pm line 161.
> > [Tue Mar 20 11:47:17 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/PROGRA~1/OTRS/OTRS//Kernel/System/Log.pm line 161.
> > [Tue Mar 20 11:47:17 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/PROGRA~1/OTRS/OTRS//Kernel/System/Log.pm line 161.
> > [Tue Mar 20 11:47:17 2012] -e: Use of uninitialized value in concatenation (.) or string at C:/PROGRA~1/OTRS/OTRS//Kernel/System/Log.pm line 161.
> > ERROR: OTRS-EXT-RPC-10 Perl: 5.12.3 OS: MSWin32 Time: Tue Mar 20 11:47:17 2012
> >  Message: No StateID for 'new'!
> >  Traceback (304): 
> >    Module: Kernel::System::Ticket::TicketCreate (v1.542) Line: 419
> >    Module: Kernel::System::JoomlaGateway::TicketSubmit (unknown version) Line: 419
> >    Module: Core::Dispatch (unknown version) Line: 137
> >    Module: (eval) (unknown version) Line: 2816
> >    Module: (eval) (unknown version) Line: 2801
> >    Module: SOAP::Server::handle (unknown version) Line: 2767
> >    Module: SOAP::Transport::HTTP::Server::handle (unknown version) Line: 432
> >    Module: SOAP::Transport::HTTP::CGI::handle (unknown version) Line: 597
> >    Module: ModPerl::ROOT::ModPerl::Registry::C_3a_Programme_OTRS_OTRS_bin_cgi_2dbin_rpc_2eextended_2epl::handler (unknown version) Line: 46
> >    Module: (eval) (v1.14) Line: 204
> >    Module: ModPerl::RegistryCooker::run (v1.14) Line: 204
> >    Module: ModPerl::RegistryCooker::default_handler (v1.14) Line: 170

Herzlichen Grüße aus Hünfelden 

Marc-Oliver Widmann

((ev-it)) it-support & more | Inh. Marc-Oliver Widmann | Hehnerstrasse 7 | 65597 Hünfelden 
Tel. 06431-9499000 Fax 06431-9499009 Umsatz ID-Nr.: DE 195 381 168

Re: [OTRS-Joomla-Gateway] Unable to create ticket (#28) (20-Mrz-2012 11:44)
From:   Vittal Aithal
To:gartenlos

Hi

What appears in your OTRS system System Log when you attempt to create a ticket?

Regards
Vittal

---

**Comment by vittala** [comment]
Thanks

I'm actually interested in the OTRS System Log (http://doc.otrs.org/3.0/de/html/adminarea-system-log.html) which will list any problems that happen when the ticket is being created.

Regards
Vittal

**Comment by gartenlos** [comment]
Dienstag, 20.03.2012
SOAP Fault: (faultcode: soap:Server, faultstring: Can't use string ("Core") as a HASH ref while "strict refs" in use at C:/Programme/OTRS/OTRS/bin/cgi-bin/json.pl line 79. )

Herzlichen Grüße aus Hünfelden 

Marc-Oliver Widmann

((ev-it)) it-support & more | Inh. Marc-Oliver Widmann | Hehnerstrasse 7 | 65597 Hünfelden 
Tel. 06431-9499000 Fax 06431-9499009 Umsatz ID-Nr.: DE 195 381 168

Re: [OTRS-Joomla-Gateway] Unable to create ticket (#28) (20-Mrz-2012 11:57)
From:   Vittal Aithal
To:gartenlos

Thanks

I'm actually interested in the OTRS System Log (http://doc.otrs.org/3.0/de/html/adminarea-system-log.html) which will list any problems that happen when the ticket is being created.

Regards
Vittal

---

**Comment by vittala** [comment]
Hi Marc-Oliver

Is the 'new' state enabled and valid in your OTRS system? http://doc.otrs.org/3.1/de/html/adminarea-status.html

The json.pl is not part of the OTRS Gateway code, so any errors generated by it are caused by the iPhoneHandle package.

Regards
Vittal

**Comment by gartenlos** [comment]
Dienstag, 20.03.2012
yes, siehe bild 

Herzlichen Gre aus Hnfelden 

Marc-Oliver Widmann

((ev-it)) it-support & more | Inh. Marc-Oliver Widmann | Hehnerstrasse 7 | 65597 Hnfelden 
Tel. 06431-9499000 Fax 06431-9499009 Umsatz ID-Nr.: DE 195 381 168

**Comment by gartenlos** [comment]
Dienstag, 20.03.2012
I found the error, it was the new "neu" status. The ticket can be closed. 
Thank you very much

Herzlichen Grüße aus Hünfelden 

Marc-Oliver Widmann

((ev-it)) it-support & more | Inh. Marc-Oliver Widmann | Hehnerstrasse 7 | 65597 Hünfelden 
Tel. 06431-9499000 Fax 06431-9499009 Umsatz ID-Nr.: DE 195 381 168

Re: [OTRS-Joomla-Gateway] Unable to create ticket (#28) (20-Mrz-2012 12:45)
From:   Vittal Aithal
To:gartenlos

Hi Marc-Oliver

Is the 'new' state enabled and valid in your OTRS system? http://doc.otrs.org/3.1/de/html/adminarea-status.html

The json.pl is not part of the OTRS Gateway code, so any errors generated by it are caused by the iPhoneHandle package.

Regards
Vittal

---

**Comment by vittala** [comment]
Hi 

Glad you fixed this. I believe if you changed the name of the new state, you must also modify the configuration value Ticket::Frontend::CustomerTicketMessage###StateDefault to matched the renamed state.

Regards
Vittal
