### ISSUE TITLE
SOAP Fault: (faultcode: HTTP, faultstring: Could not connect to host)

### ISSUE THREAD

**Issue by ursus69** [cognidox/OTRS-Joomla-Gateway#33]
Hello,
After installing the Joomla gateway as per the pdf & video directions, I still have the following problem "SOAP Fault: (faultcode: HTTP, faultstring: Could not connect to host)"

I did what the PDF said, change my SOAP::lite installation, downgraded, upgraded to latest, but to no avail.

My install is Joomla 2.5.11 in a hosted domain
OTRS 3.2.8 in-house with
 Server version: Apache/2.2.22 (Ubuntu)
SOAP::Lite.......................ok (v0.715)
    o version........................ok (v0.9902)
    o Class::Inspector...............ok (v1.28)
On 
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.2 LTS
Release:    12.04
Codename:   precise

The apache server is running in the 8010 port
and my RPC_URL is:
http://hq.epet-solutions.com:8010/otrs/rpc.extended.pl
with the right SOAP_User and SOAP_pass
I can access my OTRS server with the link:
http://hq.epet-solutions.com:8010/otrs/index.pl

Any help you could provide will be greatly appreciated,

**Comment by vittala** [comment]
Hi 

Are there any firewall restrictions on your Joomla installation that would prevent a connection to port 8010 on hq.epet-solutions.com?

Also, do you see connections from your Joomla server in your Apache access log on the OTRS server?

Regards
Vittal

**Comment by ursus69** [comment]
Hello Vittal, 
Many thanks for taking the time to answer this fast.
The Firewall if off on the server behind the router and the router has the port 8010 open explicitly for the OTRS Server to be contacted from the internet, and as I said in the previous e-mail, I can connect to OTRS via the link
http://hq.epet-solutions.com:8010/otrs/index.pl
Many Thanks

Jose

**Comment by vittala** [comment]
Hi Jose

Thanks for the response.

What I'm trying to determine is if there's a firewall on the _Joomla_ server that is blocking _outbound_ traffic from the Joomla server to port 8010. If you have shell access to the Joomla server, you can test by attempting to connect to http://hq.epet-solutions.com:8010/otrs/index.pl using curl or wget.

Regards
Vittal

**Comment by ursus69** [comment]
Here my try:
bash-3.2$ wget http://hq.epet-solutions.com:8010/otrs/index.pl
--2013-07-05 10:03:51--  http://hq.epet-solutions.com:8010/otrs/index.pl
Resolving hq.epet-solutions.com... 88.184.0.159
Connecting to hq.epet-solutions.com|88.184.0.159|:8010... failed: Connection refused.

**Comment by ursus69** [comment]
Many thanks Vittal, I changed my port to classic 80 and everything is ok now
