### ISSUE TITLE
Installation failed in Joomla 1.5

### ISSUE THREAD

**Issue by Noxin** [cognidox/OTRS-Joomla-Gateway#7]
Hi,

I have just installed the Joomla component, but somehow it failed. After installing the package when clicking the component I get this error message:

Parse error: syntax error, unexpected '{' in /homepages/13/d32354364/htdocs/xxsoftware/administrator/components/com_otrsgateway/helpers/rpchelper.php on line 95

OTRS part of the installation ran without any problems.

Now I am not able to login in to the Joomla administration pages anymore... Any help would be very appreciated!

Best regards, 
Harry

**Comment by vittala** [comment]
Hi Harry

How did you install the component - via the Joomla web pages, or unzipping it into your Joomla installation?

What version of PHP are you using on your Joomla server?

Regards
Vittal

**Comment by Noxin** [comment]
Vittal, 

Thanks for answering. 

I did the install from within Joomla, just the "normal" way. Everything seemed OK as long
as I did not log out of the Joomla Administration. Trouble began when I tried to login again.

PHP Version is 4.4.9

Best regards, 
Harald

-----Ursprüngliche Nachricht-----
Von: vittala [mailto:reply@reply.github.com] 
Gesendet: Mittwoch, 23. März 2011 13:43
An: Harald Seeger
Betreff: Re: [GitHub] Installation failed in Joomla 1.5 [cognidox/OTRS-Joomla-Gateway GH-7]

Hi Harry

How did you install the component - via the Joomla web pages, or unzipping it into your Joomla installation?

What version of PHP are you using on your Joomla server?

Regards
Vittal

## 

Reply to this email directly or view it on GitHub:
https://github.com/cognidox/OTRS-Joomla-Gateway/issues/7#comment_907364

**Comment by vittala** [comment]
Hi Harald

Unfortunately, the component code requires PHP 5.x, since it uses PHP 5's exception handling model. As a result, the component won't work on your Joomla install.

To remove the component without going through the admin interface, delete the following folders from your Joomla installation:

  administrator/components/com_otrsgateway
  components/com_otrsgateway

and also remove the files:

  plugins/search/otrsgateway.php
  plugins/search/otrsgateway.xml

It's unlikely we'll provide support for PHP 4.x.

Regards
Vittal

**Comment by Noxin** [comment]
Thanks, I will try that!

-----Ursprüngliche Nachricht-----
Von: vittala [mailto:reply@reply.github.com] 
Gesendet: Mittwoch, 23. März 2011 15:00
An: Harald Seeger
Betreff: Re: [GitHub] Installation failed in Joomla 1.5 [cognidox/OTRS-Joomla-Gateway GH-7]

Hi Harald

Unfortunately, the component code requires PHP 5.x, since it uses PHP 5's exception handling model. As a result, the component won't work on your Joomla install.

To remove the component without going through the admin interface, delete the following folders from your Joomla installation:

  administrator/components/com_otrsgateway
  components/com_otrsgateway

and also remove the files:

  plugins/search/otrsgateway.php
  plugins/search/otrsgateway.xml

It's unlikely we'll provide support for PHP 4.x.

Regards
Vittal

## 

Reply to this email directly or view it on GitHub:
https://github.com/cognidox/OTRS-Joomla-Gateway/issues/7#comment_907635

**Comment by vittala** [comment]
Hi Harald

Did my suggestions get you back to a working Joomla system?

Regards
Vittal

**Comment by Noxin** [comment]
Thanks for you follow up. No, unfortunately not. I think I will have to restore a backup...

-----Ursprüngliche Nachricht-----
Von: vittala [mailto:reply@reply.github.com] 
Gesendet: Mittwoch, 30. März 2011 10:36
An: Harald Seeger
Betreff: Re: [GitHub] Installation failed in Joomla 1.5 [cognidox/OTRS-Joomla-Gateway GH-7]

Hi Harald

Did my suggestions get you back to a working Joomla system?

Regards
Vittal

## 

Reply to this email directly or view it on GitHub:
https://github.com/cognidox/OTRS-Joomla-Gateway/issues/7#comment_935231

**Comment by vittala** [comment]
Hi Harald

Just realised you should also remove the files:

plugins/authentication/otrsgateway.xml and plugins/authentication/otrsgateway.php

as these are also provided by the gateway, and may be causing PHP4 problems.

Regards
Vittal

**Comment by Noxin** [comment]
Nope... Didn't work. I am a little out of ideas what has crashed on my page. :)
Luckily I have a full backup from February.

-----Ursprüngliche Nachricht-----
Von: vittala [mailto:reply@reply.github.com] 
Gesendet: Mittwoch, 30. März 2011 10:43
An: Harald Seeger
Betreff: Re: [GitHub] Installation failed in Joomla 1.5 [cognidox/OTRS-Joomla-Gateway GH-7]

Hi Harald

Just realised you should also remove the files:

plugins/authentication/otrsgateway.xml and plugins/authentication/otrsgateway.php

as these are also provided by the gateway, and may be causing PHP4 problems.

Regards
Vittal

## 

Reply to this email directly or view it on GitHub:
https://github.com/cognidox/OTRS-Joomla-Gateway/issues/7#comment_935251

**Comment by vittala** [comment]
You can remove the files in cache/ and administrator/cache/ in your Joomla install - you're possibly getting something out of cache that's causing the problem.

Is a PHP error shown, or do you just get a blank page? There may be something of use in the web server error log.

Regards
Vittal

**Comment by Noxin** [comment]
OK,  I have deleted the cache folders. I have also deleted all the files you mentioned. Now I get a completely different error which is related
to the authentication.... Funny....

Fatal error: Call to undefined method: stdClass->onauthenticate() in /homepages/11/d17357064/htdocs/mrsoftware/libraries/joomla/user/authentication.php on line 121

-----Ursprüngliche Nachricht-----
Von: vittala [mailto:reply@reply.github.com] 
Gesendet: Mittwoch, 30. März 2011 10:53
An: Harald Seeger
Betreff: Re: [GitHub] Installation failed in Joomla 1.5 [cognidox/OTRS-Joomla-Gateway GH-7]

You can remove the files in cache/ and administrator/cache/ in your Joomla install - you're possibly getting something out of cache that's causing the problem.

Is a PHP error shown, or do you just get a blank page? There may be something of use in the web server error log.

Regards
Vittal

## 

Reply to this email directly or view it on GitHub:
https://github.com/cognidox/OTRS-Joomla-Gateway/issues/7#comment_935273

**Comment by vittala** [comment]
Ah, that makes a bit of sense. It's still got a reference to the authentication plugin in the database, and is attempting to load a non-existent class (I was hoping Joomla would be a bit smarter). However, this can be fixed by zapping the plugin reference in the database:

UPDATE plugins SET published = 0 WHERE element = 'otrsgateway';

(you may need to change the table name to include your Joomla install's table prefix).

Once done, Joomla will no longer attempt to load the gateway plugins, and should proceed as normal.

Regards
Vittal

**Comment by Noxin** [comment]
Vittal, 

You are my hero! I did not recognize the plugins, too. That was easy. It's working again.
I have also changed the webserver configuration to PHP5. So I could give it  another try. 

Thank you very much for your great support!!!

Regards, 
Harald

-----Ursprüngliche Nachricht-----
Von: vittala [mailto:reply@reply.github.com] 
Gesendet: Mittwoch, 30. März 2011 11:28
An: Harald Seeger
Betreff: Re: [GitHub] Installation failed in Joomla 1.5 [cognidox/OTRS-Joomla-Gateway GH-7]

Ah, that makes a bit of sense. It's still got a reference to the authentication plugin in the database, and is attempting to load a non-existent class (I was hoping Joomla would be a bit smarter). However, this can be fixed by zapping the plugin reference in the database:

UPDATE plugins SET published = 0 WHERE element = 'otrsgateway';

(you may need to change the table name to include your Joomla install's table prefix).

Once done, Joomla will no longer attempt to load the gateway plugins, and should proceed as normal.

Regards
Vittal

## 

Reply to this email directly or view it on GitHub:
https://github.com/cognidox/OTRS-Joomla-Gateway/issues/7#comment_935374

**Comment by vittala** [comment]
Hi Harald

Glad you're back up and running. 

If it's useful for you under PHP 5, please feel free to vote for it at http://extensions.joomla.org/extensions/clients-a-communities/crm-bridges/14455 :)

Regards
Vittal
